AZURE_STORAGE_ACCOUNT_NAME = "cortevachurn8137872830"
AZURE_STORAGE_ACCOUNT_KEY = "Tx2wx+Bp8oH6Xf3aSYlS2qSy+SOw3gOQ+Dq+xWqgttlAsSaErAqRBIjytpnJ24GlF4uSmZx2BYNiqjQfWPxCXg=="
AZURE_STORAGE_CONTAINER_NAME = "uploaded-blob"
AZURE_STORAGE_USE_HTTPS= "https://cortevachurn8137872830.blob.core.windows.net/"
ACTIVITIES_FILENAME="activities"
TRANSACTIONS_FILENAME="transactions"
URL_RETURN="https://cortevachurn8137872830.blob.core.windows.net/uploaded-blob/activities.csv"
